spring.datasource.url=jdbc:sqlserver://localhost;databaseName=banking_app;encrypt=true;trustServerCertificate=true
spring.datasource.username=banking_user
spring.datasource.password=StrongPass123!

spring.jpa.hibernate.ddl-auto=update
